/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LSMS;

import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mr Olayinka
 */
public class Attendance_Search extends javax.swing.JDialog {

   
     ResultSet rs=null ;
     Connection conn = null;
      Statement st = null;
      
    public Attendance_Search(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       
        initComponents();
          ClockThread3 k = new ClockThread3();
         k.start();
       
        MatricTB.setVisible(false); 
       DateconTB.setVisible(false);
        RadioDate.setSelected(true);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        datebutton = new javax.swing.JButton();
        MatricTB = new javax.swing.JTextField();
        RadioMatricNo = new javax.swing.JRadioButton();
        RadioDate = new javax.swing.JRadioButton();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        DateconTB = new javax.swing.JTextField();
        lons = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableS = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Attendance");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        datebutton.setText("Date");
        datebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datebuttonActionPerformed(evt);
            }
        });

        MatricTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatricTBActionPerformed(evt);
            }
        });
        MatricTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MatricTBKeyReleased(evt);
            }
        });

        RadioMatricNo.setText("By MatricNo");
        RadioMatricNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMatricNoActionPerformed(evt);
            }
        });

        RadioDate.setText(" By Date");
        RadioDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioDateActionPerformed(evt);
            }
        });

        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadioMatricNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MatricTB, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioDate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DateconTB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(RadioMatricNo)
                    .addComponent(RadioDate)
                    .addComponent(datebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MatricTB)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateconTB))
                .addContainerGap())
        );

        lons.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lons.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Date/Time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 12))); // NOI18N

        TableS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lons, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lons, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatricTBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MatricTBKeyReleased
        try {
            conn = SqlConnect2.AttconDB();
            st = conn.createStatement();
            
            String p ="select nn.ID , nn.FirstName , nn.LastName ,nnsignin.TimeIN,nnsignin.Status ,nnsignin.ReasonForLateness ,nnsignin.Date ,nnsignin.TimeOut from nn,nnsignin where nn.ID = nnsignin.TempID  and nn.MatricNo='"+MatricTB.getText().toUpperCase()+"'";
            rs = st.executeQuery(p);
            TableS.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            st.close();
          
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this,ex);
        } catch (IOException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
             JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_MatricTBKeyReleased

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("M/d/yyyy");
        String s = sdf.format(jXDatePicker1.getDate());
       DateconTB.setText(s);
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void RadioMatricNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMatricNoActionPerformed
      
//        RadioAbsentees.setSelected(false);
        RadioDate.setSelected(false);
        MatricTB.setVisible(true); 
         MatricTB.requestFocus(); 
        jXDatePicker1.setVisible(false);
        datebutton.setVisible(false);
               DefaultTableModel dtm = (DefaultTableModel) TableS.getModel();
                dtm.setRowCount(0);
                
       
    }//GEN-LAST:event_RadioMatricNoActionPerformed

    private void RadioDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioDateActionPerformed
    RadioMatricNo.setSelected(false);
//       RadioAbsentees.setSelected(false);
        MatricTB.setVisible(false); 
        jXDatePicker1.setVisible(true);
        datebutton.setVisible(true);              
        
        DefaultTableModel dtm = (DefaultTableModel) TableS.getModel();
                dtm.setRowCount(0);
    }//GEN-LAST:event_RadioDateActionPerformed

    private void datebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datebuttonActionPerformed
      
        
        try {
            conn = SqlConnect2.AttconDB();
            st = conn.createStatement();
            
            String p ="select nn.ID as 'ID', nn.FirstName as 'FirstName', nn.LastName as 'LastName',nn.MatricNo as 'MatricNo',nnsignin.TimeIN as 'TimeIN',nnsignin.Status as'Status',nnsignin.ReasonForLateness as'ReasonForLateness',nnsignin.TimeOut as 'TimeOut' from nn,nnsignin where nn.ID = nnsignin.TempID  and nnsignin.Date='"+DateconTB.getText()+"'";
            rs = st.executeQuery(p);
            TableS.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            st.close();
          
        } catch (SQLException | IOException ex) {
             JOptionPane.showMessageDialog(this,ex);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
             JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_datebuttonActionPerformed

    private void MatricTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatricTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatricTBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Attendance_Search dialog = new Attendance_Search(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateconTB;
    private javax.swing.JTextField MatricTB;
    private javax.swing.JRadioButton RadioDate;
    private javax.swing.JRadioButton RadioMatricNo;
    private javax.swing.JTable TableS;
    private javax.swing.JButton datebutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    public static javax.swing.JLabel lons;
    // End of variables declaration//GEN-END:variables
}
