/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LSMS;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Mr Olayinka
 */
public class Attendance_Record extends javax.swing.JFrame {

    
       
      Statement st = null;
        PreparedStatement pst=null;
          String ct;
        ResultSet rs=null ;
    
        Connection conn = null;
    /**
     * Creates new form Attendance_Data
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public Attendance_Record() throws SQLException, ClassNotFoundException, IOException, IllegalAccessException, InstantiationException {
        initComponents();
        setLocationRelativeTo(this);
        StdTable();
    }

    
    public void StdTable() throws SQLException, ClassNotFoundException, IOException, IllegalAccessException, InstantiationException{
        //Class.forName("com.mysql.jdbc.Driver");
           Class.forName("org.sqlite.JDBC");
 conn = SqlConnect2.AttconDB();
                     st = conn.createStatement();
   
      String p ="select nn.MatricNo as 'MatricNo',nnsignin.TimeIN as 'TimeIN',nnsignin.Status as'Status',nnsignin.ReasonForLateness as'ReasonForLateness',nnsignin.Date as'Date',nnsignin.TimeOut as 'TimeOut' from nn,nnsignin where nn.ID = nnsignin.TempID ";
                        rs = st.executeQuery(p);
                       ID_Table.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            st.close();
            conn.close();
            
//              try {
//            MessageFormat h = new MessageFormat("Attendance Report ");
//           
//
//            ID_Table.print(JTable.PrintMode.NORMAL, h, null);
//
//        } catch (PrinterException ex) {
//            Logger.getLogger(Attendance_Record.class.getName()).log(Level.SEVERE, null, ex);
//        }
//            
                        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ID_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Attendance Records");

        ID_Table.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ID_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ID_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(ID_Table);
        if (ID_Table.getColumnModel().getColumnCount() > 0) {
            ID_Table.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            ID_Table.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            ID_Table.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            ID_Table.getColumnModel().getColumn(3).setHeaderValue("Title 4");
            ID_Table.getColumnModel().getColumn(4).setHeaderValue("Title 5");
            ID_Table.getColumnModel().getColumn(5).setHeaderValue("Title 6");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Attendance_Record().setVisible(true);
                } catch (SQLException | ClassNotFoundException | IOException | IllegalAccessException | InstantiationException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ID_Table;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
