/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LSMS;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Mr Olayinka
 */
public class By_Students_ID extends javax.swing.JDialog implements ActionListener{

    ResultSet rs=null ;
     Connection conn = null;
      Statement st = null;
       PreparedStatement pst=null;
       public static  JFreeChart   PieChart;
       public static  ChartFrame chartPanel;
       public static String ct;
        JButton save;
        
        
    public By_Students_ID(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
            setLocationRelativeTo(parent);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SRTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        SRTable.setAutoCreateRowSorter(true);
        SRTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        SRTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        SRTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        SRTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SRTable.setSelectionBackground(new java.awt.Color(0, 102, 255));
        SRTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SRTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SRTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SRTable);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SearchData", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setText("ID");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField1InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField1PropertyChange(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LSMS/000000.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SRTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SRTableMouseClicked
       
        try {
            String jj="";
            Class.forName("org.sqlite.JDBC");
            conn = SqlConnect2.conDB();

            int row = SRTable.getSelectedRow();
              ct = ( SRTable.getModel().getValueAt(row, 0).toString());

            DefaultPieDataset ds = new DefaultPieDataset();

            st = conn.createStatement();
            String p ="select ID,MatricNo,FirstName,MiddleName,LastName,Level,Course,Level_100_FirstSemester_GP,Level_100_SecondSemester_GP, Level_100_Final_CGPA ,  Level_200_FirstSemester_GP , Level_200_SecondSemester_GP , Level_200_Final_CGPA,   Level_300_FirstSemester_GP , Level_300_SecondSemester_GP, Level_300_Final_CGPA , Level_400_FirstSemester_GP , Level_400_SecondSemester_GP , Level_400_Final_CGPA from tblstudents where ID='"+ct+"' ";
            rs = st.executeQuery(p);
            while (rs.next()){

                String ID = rs.getString("ID");
                String FirstName = rs.getString("FirstName");
                String MiddleName = rs.getString("MiddleName");
                String LastName = rs.getString("LastName");
                String mtn = rs.getString("MatricNo");
                jj = ID + " - "+ mtn +" - "+ FirstName +" "+MiddleName+" "+ LastName;

                float as = rs.getFloat("Level_100_FirstSemester_GP") ;
                float  b = rs.getFloat("Level_100_SecondSemester_GP");
                float c1 = rs.getFloat("Level_100_Final_CGPA");
                float  d = rs.getFloat("Level_200_FirstSemester_GP");
                float  e = rs.getFloat("Level_200_SecondSemester_GP");
                float  f = rs.getFloat("Level_200_Final_CGPA");
                float  g = rs.getFloat("Level_300_FirstSemester_GP");
                float h = rs.getFloat("Level_300_SecondSemester_GP");
                float  i = rs.getFloat("Level_300_Final_CGPA");
                float   j1 = rs.getFloat("Level_400_FirstSemester_GP");
                float   k = rs.getFloat("Level_400_SecondSemester_GP");
                float   l = rs.getFloat("Level_400_Final_CGPA");

                // SETS PIE CHART VALUES

                ds.setValue("100L FirstSemester GPA", as);
                ds.setValue("100L SecondSemester GPA", b);
                ds.setValue("100L Final CGPA", c1);
                ds.setValue("200L FirstSemester GPA", d);
                ds.setValue("200L SecondSemester GPA", e);
                ds.setValue("200L Final CGPA", f);
                ds.setValue("300L FirstSemester GPA", g);
                ds.setValue("300L SecondSemester GPA", h);
                ds.setValue("300L Final CGPA", i);
                ds.setValue("400L FirstSemester GPA", j1);
                ds.setValue("400L SecondSemester GPA", k);
                ds.setValue("400L Final CGPA", l);

            }

            
             PieChart = ChartFactory.createPieChart3D(jj, ds,true,true,true);
             
            PieChart.setBackgroundPaint(Color.pink);

          chartPanel = new ChartFrame("Student Record Chart", PieChart  );

            chartPanel.setSize(600, 400);
            chartPanel.setLocationRelativeTo(null);
            this.dispose();
            chartPanel.setVisible(true);
   
            chartPanel .addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent evt) {

                     chartPanel.dispose();
                    By_Students_ID g = new By_Students_ID(null,true);
                    g.setVisible(true);
                   
                };
            });

        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error :" +ex.getMessage());
        } catch (IOException | InstantiationException | IllegalAccessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
             
    }//GEN-LAST:event_SRTableMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained

    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost

    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField1InputMethodTextChanged

    }//GEN-LAST:event_jTextField1InputMethodTextChanged

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange

    }//GEN-LAST:event_jTextField1PropertyChange

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
   
    
        try {
            Class.forName("org.sqlite.JDBC");
            conn = SqlConnect2.conDB();
            String search =  (jTextField1.getText());
            //           String sql2 = "Select ID from tblstudents where id ='"+search+"' ";  //checks if the ID Exists  in the Database
            //               pst= conn.prepareStatement(sql2);
            //                rs=pst.executeQuery();
            //                 if (rs.next()){}
            //                      else{ DefaultTableModel t = (DefaultTableModel)SRTable.getModel();
                //                      t.setRowCount(0);
                //                     JOptionPane.showMessageDialog(this,"ID Doesnt Exist !!");return;}

        
            String p ="select ID,MatricNo,FirstName,MiddleName,LastName,Level,Course,Level_100_FirstSemester_GP,Level_100_SecondSemester_GP, Level_100_Final_CGPA ,  Level_200_FirstSemester_GP , Level_200_SecondSemester_GP , Level_200_Final_CGPA,   Level_300_FirstSemester_GP , Level_300_SecondSemester_GP, Level_300_Final_CGPA , Level_400_FirstSemester_GP , Level_400_SecondSemester_GP , Level_400_Final_CGPA from tblstudents where id =?   ";
            pst = conn.prepareStatement(p);
            pst.setString(1, search);
            rs = pst.executeQuery();
            SRTable.setModel(DbUtils.resultSetToTableModel(rs));
 
        } catch (SQLException | ClassNotFoundException | IOException | InstantiationException | IllegalAccessException ex) {
            JOptionPane.showMessageDialog(null,ex);

        }finally{

            try {
                rs.close();
                pst.close();
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(By_Students_ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(By_Students_ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(By_Students_ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(By_Students_ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                By_Students_ID dialog = new By_Students_ID(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable SRTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
