/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LSMS;



import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;



/**
 *
 * @author Mr Olayinka
 */
public class Signin extends javax.swing.JFrame {

    
     
           
     Connection conn = null;
      Statement st = null;
      ResultSet rs = null;
      
    public Signin() {
        initComponents();
       setLocationRelativeTo(null);
//       zero.setVisible(false);
//       Path currentRelativePath = Paths.get("");
//String s = currentRelativePath.toAbsolutePath().toString();
//System.out.println("Current relative path is: " + s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setTitle("LSMS");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SignIn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arabic Typesetting", 3, 24), javax.swing.UIManager.getDefaults().getColor("TabRenderer.selectedActivatedBackground"))); // NOI18N

        jLabel2.setText("User Name");

        jLabel1.setText("Password");

        ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDKeyTyped(evt);
            }
        });

        jButton1.setText("LogIn");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("New Admin");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.setEnabled(false);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LSMS/yImg5.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPasswordField1)
                                .addGap(5, 5, 5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
      public  static void  Progress() throws InterruptedException{ 
          
          final JFrame g = new JFrame();
          g.setUndecorated(true);
          g.setSize(124, 49);
          ImageIcon icon = new ImageIcon("src/wait.gif");
          g.add(new JLabel(" Please Wait...", icon, JLabel.CENTER));
          g.setLocationRelativeTo(null);
          
        SwingWorker<String, Void>
                  worker = new SwingWorker<String, Void>() {
              @Override
              protected String doInBackground() throws Exception {
                  Thread.sleep(5000);
                  Main  o = new Main();
                 o.setVisible(true);
                  return null;
              }
                @Override
                  protected void done(){
                       
                 g.dispose();
               
                               }
                  
          };
          worker.execute();
        
            g.setVisible(true);
    
      }
      
      
      
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         
        String password = String.valueOf(jPasswordField1.getPassword());
        
        if(ID.getText().equals("") || ( password .equals("")))  {
            
        JOptionPane.showMessageDialog(null, "Fill up Fields" );
        
        return;
        }
        
        try{
            Class.forName("org.sqlite.JDBC");
       
               conn = SqlConnect2.AdminconDB();
                 
                        st = conn.createStatement();

                         rs = st.executeQuery("select * from Admin where UserName ='"+ID.getText()+"' and Password = '"+ password +"'  ");
                        if (rs.next()){
                               this.dispose();
                           
                            Progress();
                        }
                        else{
                           
                            JOptionPane.showMessageDialog(this, "LogIn Failed, Try Again!!!", "SignIn Error" , JOptionPane.ERROR_MESSAGE);
 
                        }

                ID  .setText("");
               jPasswordField1.setText("");
               
        }
            catch(SQLException ex){
            JOptionPane.showMessageDialog(null, " SQLException :  "+ ex);

        }
        catch(ClassNotFoundException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
        } catch (IOException | InstantiationException | IllegalAccessException ex) {
              JOptionPane.showMessageDialog(null, ex);
         } catch (InterruptedException ex) {
             Logger.getLogger(Signin.class.getName()).log(Level.SEVERE, null, ex);
         }finally{
            if (conn!=null){
                try {
                    conn.close();
                    
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, "Error : \n" +ex.getMessage());
                }}
            }
        
    }//GEN-LAST:event_jButton1MouseClicked

    
    public void close(){
            //WindowEvent windowclosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING );
           // Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowclosing);
    
    
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 
    }//GEN-LAST:event_formWindowOpened

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      this.dispose();
        Admin_New na = new Admin_New(this,true) ;
       na.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
       
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
             String password = String.valueOf(jPasswordField1.getPassword());
        
        if(ID.getText().equals("") || ( password .equals("")))  {
            
        JOptionPane.showMessageDialog(null, "Fill up Fields" );
        
        return;
        }
        
           try {
                Class.forName("org.sqlite.JDBC");
               conn = SqlConnect2.AdminconDB();
               
              st = conn.createStatement();
            
               
               rs = st.executeQuery("select * from Admin where UserName ='"+ID.getText()+"' and Password = '"+ password +"'  ");
               if (rs.next()){
                   this.dispose();
                   
                    Progress();
                     
                   
               }
               else{
                   
                   JOptionPane.showMessageDialog(this, "LogIn Failed, Try Again!!!", "SignIn Error" , JOptionPane.ERROR_MESSAGE);
                   
               }
               
               ID.setText("");
               jPasswordField1.setText("");
               
               
           } catch (SQLException | ClassNotFoundException ex) {
               JOptionPane.showMessageDialog(null, ex);
           } catch (IOException | InstantiationException | IllegalAccessException ex) {
                JOptionPane.showMessageDialog(null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Signin.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
            if (conn!=null){
                try {
                    conn.close();
                    
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, "Error : \n" +ex.getMessage());
                }}
            }
        
       
       }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDKeyTyped
     char f = evt.getKeyChar();
     if((Character.isDigit(f)) || (evt.getKeyCode() == KeyEvent.VK_SPACE  )){
      
     evt.consume();
     }
    }//GEN-LAST:event_IDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
         
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signin().setVisible(true);
            }
        });
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
