/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LSMS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import static LSMS.Student_Update.c;
import static LSMS.Student_Update.fn;
import static LSMS.Student_Update.id;
import static LSMS.Student_Update.lev;
import static LSMS.Student_Update.ln;
import static LSMS.Student_Update.mn;
import java.io.IOException;

/**
 *
 * @author Mr Olayinka
 */
public class Student_RecordTable1 extends javax.swing.JFrame {

    
     ResultSet rs=null ;
     Connection conn = null;
      PreparedStatement pst = null;
       public static String a,b,c1,d,e,f,g,h,i ,j1,k,l,mtn;
       public static String ctt;
      
    public Student_RecordTable1() throws SQLException, ClassNotFoundException, IOException, InstantiationException, IllegalAccessException {
        initComponents();
        
        setLocationRelativeTo(this);
        StdTable() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        srecortable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student_Record Table1");

        srecortable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        srecortable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        srecortable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        srecortable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                srecortableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(srecortable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srecortableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srecortableMouseClicked
        try {

                         int row = srecortable.getSelectedRow();
                                ctt = ( srecortable.getModel().getValueAt(row, 0).toString());    
  
                         String p ="select ID,MatricNo,FirstName,MiddleName,LastName,Level,Course,Level_100_FirstSemester_GP,Level_100_SecondSemester_GP, Level_100_Final_CGPA ,  Level_200_FirstSemester_GP , Level_200_SecondSemester_GP , Level_200_Final_CGPA,   Level_300_FirstSemester_GP , Level_300_SecondSemester_GP, Level_300_Final_CGPA , Level_400_FirstSemester_GP , Level_400_SecondSemester_GP , Level_400_Final_CGPA from tblstudents where ID = '"+ctt+"' ";
                          pst = conn.prepareStatement(p);
                        rs = pst.executeQuery();
                        
                    while(rs.next()){
                        id = rs.getString("ID");
                        fn = rs.getString("FirstName");
                        mn = rs.getString("MiddleName");
                        ln = rs.getString("LastName");
                        c = rs.getString("Course");  
                         lev= rs.getString("Level");
                         mtn =rs.getString("MatricNo");        
              a = rs.getString("Level_100_FirstSemester_GP") ;
               b = rs.getString("Level_100_SecondSemester_GP");
                c1 = rs.getString("Level_100_Final_CGPA");    
                  d = rs.getString("Level_200_FirstSemester_GP");
                   e = rs.getString("Level_200_SecondSemester_GP");
                    f = rs.getString("Level_200_Final_CGPA");
                     g = rs.getString("Level_300_FirstSemester_GP");
                      h = rs.getString("Level_300_SecondSemester_GP");
                        i = rs.getString("Level_300_Final_CGPA");
                         j1 = rs.getString("Level_400_FirstSemester_GP");
                           k = rs.getString("Level_400_SecondSemester_GP");
                             l = rs.getString("Level_400_Final_CGPA");         
                    }     
                     this.dispose();
                     
                      Student_Record j = new Student_Record(this,true);
                      j.IDTextField.setText(id);
                    Student_Record.FirstNameTextField.setText(fn);
               Student_Record. MiddleNameTextField.setText(mn);
                Student_Record.LastNameTextField.setText(ln);
                Student_Record.CourseComboBox.setSelectedItem(c);
                 Student_Record. LevelComboBox.setSelectedItem(lev);
                 Student_Record.matnotb.setText(mtn);
                         
                    j.GPFs100jTextField.setText(a);
                     j.GPSs100jTextField.setText(b);
                      j.CGPA100jTextField.setText(c1);
                       j.GPFs200jTextField.setText(d);
                        j.GPSs200jTextField.setText(e);
                         j.CGPA200jTextField.setText(f);
                          j.GPFs300jTextField.setText(g);
                           j.GPSs300jTextField.setText(h);
                            j.CGPA300jTextField.setText(i);
                             j.GPFs400jTextField.setText(j1);
                              j.GPSs400jTextField.setText(k);
                              j.CGPA400jTextField.setText(l);
                     j.setVisible(true);
    rs.close();
    pst.close();

        } catch (SQLException ex) {       
            JOptionPane.showMessageDialog(this,ex);
        }
        
    }//GEN-LAST:event_srecortableMouseClicked

    
    public final void StdTable() throws SQLException, ClassNotFoundException, IOException, InstantiationException, IllegalAccessException{
        //Class.forName("com.mysql.jdbc.Driver");
           Class.forName("org.sqlite.JDBC");
           conn=SqlConnect2.conDB();
                    String p ="select ID,MatricNo,FirstName,MiddleName,Level,Course from tblstudents ";
                  /*  ,Level,Course,Level_100_FirstSemester_GP,Level_100_SecondSemester_GP, Level_100_Final_CGPA ,  Level_200_FirstSemester_GP , Level_200_SecondSemester_GP , Level_200_Final_CGPA,   Level_300_FirstSemester_GP , Level_300_SecondSemester_GP, Level_300_Final_CGPA , Level_400_FirstSemester_GP , Level_400_SecondSemester_GP , Level_400_Final_CGPA */
                       pst = conn.prepareStatement(p);
                    rs = pst.executeQuery();          
                        LSMS.Student_RecordTable1.srecortable.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
                pst.close();
               
                  
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
         //</editor-fold>
         //</editor-fold>
         
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    
                    new Student_RecordTable1().setVisible(true);
                    
                } catch (SQLException | ClassNotFoundException | IOException | InstantiationException | IllegalAccessException ex) {
                      JOptionPane.showMessageDialog(null,ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable srecortable;
    // End of variables declaration//GEN-END:variables
}
