/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LSMS;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static LSMS.Student_Record.CourseComboBox;
import static LSMS.Student_Record.FirstNameTextField;
import static LSMS.Student_Record.LastNameTextField;
import static LSMS.Student_Record.LevelComboBox;
import static LSMS.Student_Record.MiddleNameTextField;
import static LSMS.Student_Record.matnotb;
import java.io.IOException;

/**
 *
 * @author Mr Olayinka
 */
public class Student_Record extends javax.swing.JDialog {

    
   
     Connection conn ;
      PreparedStatement pst  ;
      
    public Student_Record(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        ViewRecordsButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        MiddleNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        CourseComboBox = new javax.swing.JComboBox();
        LevelComboBox = new javax.swing.JComboBox();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        GPFs100jTextField = new javax.swing.JTextField();
        GPSs100jTextField = new javax.swing.JTextField();
        CGPA100jTextField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        GPFs200jTextField = new javax.swing.JTextField();
        GPSs200jTextField = new javax.swing.JTextField();
        CGPA200jTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        GPFs300jTextField = new javax.swing.JTextField();
        GPSs300jTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CGPA300jTextField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        GPFs400jTextField = new javax.swing.JTextField();
        GPSs400jTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        CGPA400jTextField = new javax.swing.JTextField();
        IDTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        matnotb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        ViewRecordsButton.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        ViewRecordsButton.setText("View Records");
        ViewRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRecordsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ViewRecordsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Student Record"));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setText("∞");
        jButton4.setPreferredSize(new java.awt.Dimension(41, 21));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("FirstName");
        jLabel3.setMaximumSize(new java.awt.Dimension(76, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(76, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(76, 14));

        FirstNameTextField.setEditable(false);

        MiddleNameTextField.setEditable(false);
        MiddleNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel4.setText("MiddleName");
        jLabel4.setPreferredSize(new java.awt.Dimension(76, 14));

        jLabel2.setText("LastName");
        jLabel2.setMaximumSize(new java.awt.Dimension(76, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(76, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(76, 14));

        LastNameTextField.setEditable(false);

        CourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Course...", "Accounting", "Bio Chemistry", "Computer Science", "Economics", "Industrial Chemistry", "Micro Biology", "Mass Comm", "Banking and Finanace" }));
        CourseComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CourseComboBox.setEnabled(false);
        CourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseComboBoxActionPerformed(evt);
            }
        });

        LevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose  Level...", "100", "200", "300", "400", "500" }));
        LevelComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LevelComboBox.setEnabled(false);
        LevelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelComboBoxActionPerformed(evt);
            }
        });

        jLabel64.setText("Level");
        jLabel64.setPreferredSize(new java.awt.Dimension(76, 14));

        jLabel65.setText("Course");
        jLabel65.setPreferredSize(new java.awt.Dimension(76, 14));

        jTabbedPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        GPFs100jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPFs100jTextFieldActionPerformed(evt);
            }
        });
        GPFs100jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GPFs100jTextFieldKeyTyped(evt);
            }
        });

        GPSs100jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GPSs100jTextFieldKeyTyped(evt);
            }
        });

        CGPA100jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CGPA100jTextFieldKeyTyped(evt);
            }
        });

        jLabel27.setText("100 Level CGPA");

        jLabel28.setText("Second Semester GP");

        jLabel29.setText("First Semester GP");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(GPFs100jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GPSs100jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CGPA100jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPFs100jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPSs100jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CGPA100jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("100Level", jPanel10);

        GPFs200jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GPFs200jTextFieldKeyTyped(evt);
            }
        });

        GPSs200jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GPSs200jTextFieldKeyTyped(evt);
            }
        });

        CGPA200jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CGPA200jTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CGPA200jTextFieldKeyTyped(evt);
            }
        });

        jLabel1.setText("First Semester GP");

        jLabel17.setText("Second Semester GP");

        jLabel18.setText("200 Level CGPA");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(24, 24, 24)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GPFs200jTextField)
                    .addComponent(GPSs200jTextField)
                    .addComponent(CGPA200jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPFs200jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPSs200jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CGPA200jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("200Level", jPanel7);

        jLabel19.setText("First Semester GP");

        GPFs300jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GPFs300jTextFieldKeyTyped(evt);
            }
        });

        GPSs300jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GPSs300jTextFieldKeyTyped(evt);
            }
        });

        jLabel20.setText("Second Semester GP");

        jLabel21.setText("300 Level CGPA");

        CGPA300jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CGPA300jTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GPFs300jTextField)
                    .addComponent(CGPA300jTextField)
                    .addComponent(GPSs300jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(GPFs300jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPSs300jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CGPA300jTextField)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("300Level", jPanel8);

        jLabel22.setText("First Semester GP");

        GPFs400jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPFs400jTextFieldActionPerformed(evt);
            }
        });
        GPFs400jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GPFs400jTextFieldKeyTyped(evt);
            }
        });

        GPSs400jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GPSs400jTextFieldKeyTyped(evt);
            }
        });

        jLabel23.setText("Second Semester GP");

        jLabel24.setText("400 Level CGPA");

        CGPA400jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CGPA400jTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GPFs400jTextField)
                    .addComponent(GPSs400jTextField)
                    .addComponent(CGPA400jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(GPFs400jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPSs400jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CGPA400jTextField)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("400Level", jPanel9);

        IDTextField.setEditable(false);

        jLabel14.setText("ID");

        matnotb.setEditable(false);

        jLabel6.setText("Matric No");
        jLabel6.setMaximumSize(new java.awt.Dimension(76, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(76, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(76, 14));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(87, 87, 87)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matnotb, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LastNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MiddleNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LevelComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CourseComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 143, Short.MAX_VALUE)
                                    .addComponent(IDTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MiddleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matnotb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LSMS/xImg8.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Resetform(){
     
                    IDTextField.setText("");
                   FirstNameTextField.setText("");
               MiddleNameTextField.setText("");
                LastNameTextField.setText("");
               CourseComboBox.setSelectedIndex(0);
                  LevelComboBox.setSelectedIndex(0);
                  matnotb.setText("");
               CGPA100jTextField.setText("");
     CGPA200jTextField.setText("");
CGPA300jTextField.setText("");
    CGPA400jTextField.setText("");
       GPFs100jTextField.setText("");
    GPFs200jTextField.setText("");
     GPFs300jTextField.setText("");
     GPFs400jTextField.setText("");
 GPSs100jTextField.setText("");
 GPSs200jTextField.setText("");
   GPSs300jTextField.setText("");
    GPSs400jTextField.setText("");
 }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if((FirstNameTextField.getText().equals(""))||
            (MiddleNameTextField.getText().equals(""))||(LastNameTextField.getText().equals("")) || (matnotb.getText().equals(""))||
            (CourseComboBox.getSelectedItem().equals("Select a Course...")) ||(LevelComboBox.getSelectedItem().equals("Choose  Level..."))  ){

            JOptionPane.showMessageDialog(null, " No Record To Save !  ");
            return;
        }

        try{
           
           
            String add = "update  tblstudents set  Level_100_FirstSemester_GP ='"+ GPFs100jTextField.getText() + "', Level_100_SecondSemester_GP ='"+ GPSs100jTextField.getText()  + "',   Level_100_Final_CGPA ='"+ CGPA100jTextField.getText()  + "',  Level_200_FirstSemester_GP ='"+ GPFs200jTextField.getText() + "',  Level_200_SecondSemester_GP ='"+ GPSs200jTextField.getText() + "', Level_200_Final_CGPA ='"+ CGPA200jTextField.getText() + "', Level_300_FirstSemester_GP ='"+ GPFs300jTextField.getText()  + "', Level_300_SecondSemester_GP ='"+ GPSs300jTextField.getText() + "', Level_300_Final_CGPA ='"+ CGPA300jTextField.getText() + "', Level_400_FirstSemester_GP ='"+ GPFs400jTextField.getText() + "' ,  Level_400_SecondSemester_GP ='"+GPSs400jTextField.getText()  + "',  Level_400_Final_CGPA ='"+ CGPA400jTextField.getText() + "'  where ID ='"+IDTextField.getText()+"' ";
             pst = conn.prepareStatement(add);
            pst.execute();

            Resetform();
            JOptionPane.showMessageDialog( this, "Record Saved","Student Record", JOptionPane.INFORMATION_MESSAGE);

            
        }catch(HeadlessException | SQLException ex){
           JOptionPane.showMessageDialog(null, ex);
        } finally{
            if ((conn!= null) || (conn == null)){
                try {
                    pst.close();
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                }
            }

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void ViewRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRecordsButtonActionPerformed
        try {
            this.dispose();

            Student_RecordTable2 g = new Student_RecordTable2(null, true);
            g.setVisible(true);
        } catch (SQLException | ClassNotFoundException | IOException | InstantiationException | IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }

    }//GEN-LAST:event_ViewRecordsButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            this.dispose();
            Student_RecordTable1 frm = new Student_RecordTable1();
            frm.setVisible(true);

        } catch (SQLException | ClassNotFoundException | IOException | InstantiationException | IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseComboBoxActionPerformed

    private void LevelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LevelComboBoxActionPerformed

    private void GPFs100jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPFs100jTextFieldActionPerformed

    }//GEN-LAST:event_GPFs100jTextFieldActionPerformed

    private void GPFs100jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GPFs100jTextFieldKeyTyped

    }//GEN-LAST:event_GPFs100jTextFieldKeyTyped

    private void GPSs100jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GPSs100jTextFieldKeyTyped
        //          char c = evt.getKeyChar();
        //     if(!Character.isDigit(c) ||  (evt.getKeyCode() == KeyEvent.VK_SPACE)){
            //     evt.consume();
            //
            //     }
    }//GEN-LAST:event_GPSs100jTextFieldKeyTyped

    private void CGPA100jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CGPA100jTextFieldKeyTyped
        //           char c = evt.getKeyChar();
        //     if(!Character.isDigit(c) ||  (evt.getKeyCode() == KeyEvent.VK_SPACE)){
            //     evt.consume();
            //
            //     }
    }//GEN-LAST:event_CGPA100jTextFieldKeyTyped

    private void GPFs200jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GPFs200jTextFieldKeyTyped
        //          char c = evt.getKeyChar();
        //     if(!Character.isDigit(c) ||  (evt.getKeyCode() == KeyEvent.VK_SPACE)){
            //     evt.consume();
            //
            //     }
    }//GEN-LAST:event_GPFs200jTextFieldKeyTyped

    private void GPSs200jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GPSs200jTextFieldKeyTyped
        //         char c = evt.getKeyChar();
        //     if(!Character.isDigit(c) ||  (evt.getKeyCode() == KeyEvent.VK_SPACE)){
            //     evt.consume();
            //
            //     }
    }//GEN-LAST:event_GPSs200jTextFieldKeyTyped

    private void CGPA200jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CGPA200jTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CGPA200jTextFieldKeyReleased

    private void CGPA200jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CGPA200jTextFieldKeyTyped
        //         char c = evt.getKeyChar();
        //     if(!Character.isDigit(c) ||  (evt.getKeyCode() == KeyEvent.VK_SPACE)){
            //     evt.consume();
            //
            //     }
    }//GEN-LAST:event_CGPA200jTextFieldKeyTyped

    private void GPFs300jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GPFs300jTextFieldKeyTyped
        //          char c = evt.getKeyChar();
        //     if(!Character.isDigit(c) ||  (evt.getKeyCode() == KeyEvent.VK_SPACE)){
            //     evt.consume();
            //
            //     }
    }//GEN-LAST:event_GPFs300jTextFieldKeyTyped

    private void GPSs300jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GPSs300jTextFieldKeyTyped
        //         char c = evt.getKeyChar();
        //     if(!Character.isDigit(c) ||  (evt.getKeyCode() == KeyEvent.VK_SPACE)){
            //     evt.consume();
            //
            //     }
    }//GEN-LAST:event_GPSs300jTextFieldKeyTyped

    private void CGPA300jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CGPA300jTextFieldKeyTyped
        //    char c = evt.getKeyChar();
        //     if(!Character.isDigit(c) ||  (evt.getKeyCode() == KeyEvent.VK_SPACE)){
            //     evt.consume();
            //
            //     }
    }//GEN-LAST:event_CGPA300jTextFieldKeyTyped

    private void GPFs400jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPFs400jTextFieldActionPerformed

    }//GEN-LAST:event_GPFs400jTextFieldActionPerformed

    private void GPFs400jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GPFs400jTextFieldKeyTyped
        //     char c = evt.getKeyChar();
        //
        //     if(!Character.isDigit(c) ||  (evt.getKeyCode() == KeyEvent.VK_SPACE)){
            //     evt.consume();
            //     }
    }//GEN-LAST:event_GPFs400jTextFieldKeyTyped

    private void GPSs400jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GPSs400jTextFieldKeyTyped
        //        char c = evt.getKeyChar();
        //     if(!Character.isDigit(c) ||  (evt.getKeyCode() == KeyEvent.VK_SPACE)){
            //     evt.consume();
            //
            //     }
    }//GEN-LAST:event_GPSs400jTextFieldKeyTyped

    private void CGPA400jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CGPA400jTextFieldKeyTyped
        //          char c = evt.getKeyChar();
        //     if(!Character.isDigit(c) ||  (evt.getKeyCode() == KeyEvent.VK_SPACE)){
            //     evt.consume();
            //
            //     }
    }//GEN-LAST:event_CGPA400jTextFieldKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         try {
             // TODO add your handling code here:
             conn = SqlConnect2.conDB();
         } catch (IOException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
             JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Student_Record dialog = new Student_Record(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CGPA100jTextField;
    public javax.swing.JTextField CGPA200jTextField;
    public javax.swing.JTextField CGPA300jTextField;
    public javax.swing.JTextField CGPA400jTextField;
    public static javax.swing.JComboBox CourseComboBox;
    public static javax.swing.JTextField FirstNameTextField;
    public javax.swing.JTextField GPFs100jTextField;
    public javax.swing.JTextField GPFs200jTextField;
    public javax.swing.JTextField GPFs300jTextField;
    public javax.swing.JTextField GPFs400jTextField;
    public javax.swing.JTextField GPSs100jTextField;
    public javax.swing.JTextField GPSs200jTextField;
    public javax.swing.JTextField GPSs300jTextField;
    public javax.swing.JTextField GPSs400jTextField;
    public javax.swing.JTextField IDTextField;
    public static javax.swing.JTextField LastNameTextField;
    public static javax.swing.JComboBox LevelComboBox;
    public static javax.swing.JTextField MiddleNameTextField;
    public javax.swing.JButton ViewRecordsButton;
    public javax.swing.JButton btnSave;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane4;
    public static javax.swing.JTextField matnotb;
    // End of variables declaration//GEN-END:variables
}
